spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: RabbitMQApplication
server:
  port: 8080
rabbitmq:
  queue:
    name: sample-queue
  exchange:
    name: sample-exchange
  routing:
    key: key